
Insert into region  Values ('152' ,'Región de Tarapacá')
,('153' ,'Región de Antofagasta')
,('154' ,'Región de Atacama')
,('155' ,'Región de Coquimbo')
,('156' ,'Región de Valparaíso')
,('157' ,'Región del Libertador Gral. Bernardo O’Higgins')
,('158' ,'Región del Maule')
,('159' ,'Región del Biobío')
,('160' ,'Región de La Araucanía')
,('161' ,'Región de Los Lagos')
,('162' ,'Región de  Aysén del Gral.  Carlos Ibáñez del Campo')
,('163' ,'Región de Magallanes y de la Antártica Chilena')
,('164' ,'Región Metropolitana de Santiago')
,('165' ,'Región de Los Ríos')
,('166' ,'Región de Arica y Parinacota ')